name=SnappyXOExamples
version=3.0.0
author=SnappyXO
maintainer=SnappyXO
sentence=Example sketches for SnappyXO robotics kits.
paragraph=A collection of ready to use Arduino sketches for SnappyXO robots.
category=Other
url=https://github.com/snappyxo/SnappyXOExamples
architectures=*
depends=SnappyXOShield
